[tool.poetry]
name = "stage-left"
version = "0.2.0"
description = "Parse [x]it! documents into python data structures"
authors = ["chris48s"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chris48s/stage-left"
homepage = "https://github.com/chris48s/stage-left"
documentation = "https://chris48s.github.io/stage-left"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
isort = "^5.10"
flake8 = "^5.0.4"
black = "==22.10.0"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
sphinx = "^5.3.0"
sphinx-autodoc-typehints = "^1.19.5"
sphinx_rtd_theme = "^1.1.1"
myst-parser = "^0.18.1"
ghp-import = "^2.1.0"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.core.masonry.api"
